### ISSUE TITLE
Android integration not working

### ISSUE THREAD

**Issue by supagu** [ashrithks/rn-text-detector#2]
I followed your instructions to get it integrated into Android and hit this error when building:

> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/Users/fabian/Projects/jpmedia/supermarket-swap-app/android/app/build.gradle' line: 184
> 
> * What went wrong:
> A problem occurred evaluating project ':app'.
> > Supplied String module notation 'rn-text-detector' is invalid. Example notations: 'org.gradle:gradle-core:2.2', 'org.mockito:mockito-core:1.9.5:javadoc'.

**Comment by arpansharma7474** [comment]
In the android/app/build.gradle file of your project, add 

`implementation files('rn-text-detector')`

instead of 

`implementation 'rn-text-detector'`

It should compile. Enjoy coding.

**Comment by NimeshMadhushka** [comment]
> In the android/app/build.gradle file of your project, add
> 
> `implementation files('rn-text-detector')`
> 
> instead of
> 
> `implementation 'rn-text-detector'`
> 
> It should compile. Enjoy coding.


Thanks. This works

**Comment by ashrithks** [comment]
> In the android/app/build.gradle file of your project, add
> 
> `implementation files('rn-text-detector')`
> 
> instead of
> 
> `implementation 'rn-text-detector'`
> 
> It should compile. Enjoy coding.

Answer

**Comment by 1mehdifaraji** [comment]
Please update the documentation in [NPM](https://www.npmjs.com/package/rn-text-detector) 

<img width="675" alt="Screen Shot 1401-07-18 at 22 39 41" src="https://user-images.githubusercontent.com/63982703/194936612-6b40ab93-2750-4282-b7d6-ef5c4b52e017.png">

and [Github](https://github.com/ashrithks/rn-text-detector)

<img width="663" alt="Screen Shot 1401-07-18 at 22 41 23" src="https://user-images.githubusercontent.com/63982703/194936829-b21d12ba-ab46-49b1-a4c2-0ed0aabeef0a.png">

**Comment by JasonTajor** [comment]
implementation '@react-native-google-signin/google-signin'
    
    > Supplied String module notation '' is invalid. Example notations: 'org.gradle:gradle-core:2.2', 'org.mockito:mockito-core:1.9.5:javadoc'.


why is not working?
